/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import './stencil.core';




export namespace Components {

  interface MyFixedComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyFixedComponentAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'MyFixedComponent': Components.MyFixedComponent;
  }

  interface StencilIntrinsicElements {
    'my-fixed-component': Components.MyFixedComponentAttributes;
  }


  interface HTMLMyFixedComponentElement extends Components.MyFixedComponent, HTMLStencilElement {}
  var HTMLMyFixedComponentElement: {
    prototype: HTMLMyFixedComponentElement;
    new (): HTMLMyFixedComponentElement;
  };

  interface HTMLElementTagNameMap {
    'my-fixed-component': HTMLMyFixedComponentElement
  }

  interface ElementTagNameMap {
    'my-fixed-component': HTMLMyFixedComponentElement;
  }


}
